### ISSUE TITLE
works for NUC's or RPI ?

### ISSUE THREAD

**Issue by ghost** [misha-plus/power-start#1]
I have never used wake on lan.

The agent has to be running on the  server i presume.
But i dont see any code to actually make it power up or down in the Agents.

Could you explain how this works and is to be installed maybe ? Sorry about being so dumb about this.

**Comment by misha-plus** [comment]
Hello.
Server can run on Linux or Mac. Windows is probably supported too.
Agent currently supports only Unix with bash. I tested it with my Linux PC
Server and agent have no platform dependent code so you can run it.

You can pull repo, run:
`go build agent/agent.go` to get agent binary,
`go build server/*.go` to get server binary.

If you need cross-compiled version you can read this https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

Agent binary + config should be copied to target machine. Server binary + config should be copied to the server machine.

Also, you'll need to modify agent config to appropriate shutdown command + server address.
Please look here https://askubuntu.com/questions/168879/shutdown-from-terminal-without-entering-password?noredirect=1 to understand how to allow the user to shutdown machine with `sudo` but without a password.

Also, you'll need to add the agent to system auto-start. I usually do this through PM2 http://pm2.keymetrics.io/ . But you can choose systemd or similar. The server binary is also good to run through system autostart.

**Comment by misha-plus** [comment]
I marked as closed because of this just a discussion. Feel free to write additional questions at this issue.
